config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "newsletters#index"
  resources :newsletters, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  before_save :downcase_email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email,
            presence: true,
            length: { maximum: 100 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  require 'net/http'
  require 'net/https'

  def index
  end

  def create
    newsletter = Newsletter.new(newsletter_params)
    response = make_abstract_request(params[:email])
    body = JSON.parse(response.body)

    if params[:woman_fashion] == "0" and params[:man_fashion] == "0" and params[:kid_fashion] == "0"
      flash[:alert] = ['Debe de elegir, aunque sea, una de las preferencias.']
    else
      if body["quality_score"].to_f >= 0.7
        if newsletter.save
          flash[:notice] = '¡Usted se ha suscrito correctamente para recibir nuestras novedades!'
          NewsletterMailer.with(user: newsletter).suscription.deliver_now
        else
          flash[:alert] = newsletter.errors.full_messages
        end
      else
        flash[:alert] = ['El correo que introdujo, no es un correo válido. Intente con otro correo.']
      end
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def newsletter_params
    params.permit(:email, :woman_fashion, :man_fashion, :kid_fashion)
  end

  def make_abstract_request(email)
    uri = URI("https://emailvalidation.abstractapi.com/v1/?api_key=f598e161d56f4cdd9ff058bf7db78acf&email=#{email}")

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_PEER

    request =  Net::HTTP::Get.new(uri)

    response = http.request(request)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Micolet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/newsletters/index.html.erb
<% flash.each do |type, msg| %>
  <div>
    <% if type == 'notice' %>
      <%= msg %>
    <% else %>
      <ul>
        <% msg.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
<% end %>
<div class="content">
  <div class="title">
    <h1>micolet'</h1>
    <h5>Moda casi nueva con garantía</h5>
  </div>

  <div class="message">
    <h3>¡Bienvenid@! Proximamente abriremos nuestra web en este país.</h3>
    <h4>Suscríbete para recibir nuestras novedades.</h4>
  </div>

  <div class="form">
    <%= form_with url: newsletters_path do |form| %>
      <%= form.label :email, "Email" %><br>
      <%= form.email_field :email, required: true, placeholder: 'email@example.com' %><br>
      <p>Preferencias</p>
      <%= form.check_box :woman_fashion %> <%= form.label :woman_fashion, "Moda Mujer" %><br>
      <%= form.check_box :man_fashion %> <%= form.label :man_fashion, "Moda Hombre" %><br>
      <%= form.check_box :kid_fashion %> <%= form.label :kid_fashion, "Moda Infantil" %><br>
      <div class="button">
        <%= form.submit "¡Suscribirme!" %>
      </div>
    <% end %>
  </div>
</div>